CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 username VARCHAR(50) NOT NULL UNIQUE, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(16) NOT NULL CHECK(role IN ('USER','ADMIN')),
 token_version INTEGER NOT NULL DEFAULT 0 CHECK(token_version>=0)
);
CREATE TABLE auctions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 name VARCHAR(200) NOT NULL, description VARCHAR(5000) NOT NULL, condition VARCHAR(50) NOT NULL,
 image_url VARCHAR(2000), starting_price NUMERIC(19,2) NOT NULL CHECK(starting_price>0),
 current_price NUMERIC(19,2) NOT NULL CHECK(current_price>=starting_price),
 final_price NUMERIC(19,2), minimum_bid_step NUMERIC(19,2) NOT NULL CHECK(minimum_bid_step>0),
 starting_time TIMESTAMPTZ NOT NULL, ending_time TIMESTAMPTZ NOT NULL CHECK(ending_time>starting_time),
 status VARCHAR(16) NOT NULL CHECK(status IN ('SCHEDULED','ACTIVE','ENDED','FAILED')),
 winner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, winning_bid_id BIGINT
);
CREATE TABLE bids (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL,
 auction_id BIGINT NOT NULL REFERENCES auctions(id) ON DELETE CASCADE,
 bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 amount NUMERIC(19,2) NOT NULL CHECK(amount>0),
 status VARCHAR(16) NOT NULL CHECK(status IN ('WINNING','OUTBID','WON','LOST'))
);
ALTER TABLE auctions ADD FOREIGN KEY(winning_bid_id) REFERENCES bids(id) ON DELETE SET NULL;
CREATE UNIQUE INDEX bids_one_winning ON bids(auction_id) WHERE status='WINNING';
CREATE INDEX bids_auction ON bids(auction_id,id DESC);
CREATE INDEX bids_bidder ON bids(bidder_id,id DESC);
CREATE INDEX auctions_seller ON auctions(seller_id,id DESC);
CREATE INDEX auctions_due ON auctions(status,ending_time,starting_time);
